---
deployment:
  tasks:
    - export DEPLOYPATH=/homes2/sunonetes/public_html/facturacion/
    #- /bin/cp .env $DEPLOYPATH
    #- /bin/cp .htaccess $DEPLOYPATH
    - /bin/cp -R public $DEPLOYPATH
    - /bin/cp -R writable $DEPLOYPATH
    - /bin/cp -R app $DEPLOYPATH
    